### PR TITLE
completed get pizza and customer 

### PR DESCRIPTION
**Pull request by Phanx091**

### CODE REVIEW

**Review by emily-kay — COMMENTED** [review]
Remove the post since it's half finished. If you want to put the pizza name and cost in the same map, just remove the closing curly bracket to only be at the end of line 47.

**Comment by Phanx091** [comment]
updated deleted axios

**Review by emily-kay — DISMISSED** [review]

**Review by llenk — DISMISSED** [review]
Fix customer display and table

**Comment by Phanx091** [comment]
fixed pizza reducer

**Review by llenk — CHANGES_REQUESTED** [review]
-Line 16 won't work because customerReducer state is an object, and you can't put an object on the DOM. That has to be formatted.
-I'm not sure if the function in your map will return without the parentheses, since it only automatic returns if the return value starts on a single line.

**Comment by Phanx091** [comment]
fixed line 16 and line 25, parentheses

**Comment by Phanx091** [comment]
update new request

**Review by llenk — APPROVED** [review]

**Review by emily-kay — APPROVED** [review]

**Pull request merged**
