### PR TITLE
added customer reducer

### PR DESCRIPTION
**Pull request by Phanx091**
added customerReducer

### CODE REVIEW

**Review by llenk — CHANGES_REQUESTED** [review]
Customers are objects, not an array of customers. The whole thing is being sent, and it should replace whatever was in there before.

**Comment by Phanx091** [comment]
updated customer reducer fix

**Review by emily-kay — COMMENTED** [review]
Move the return empty object inside of the else if and change the end to return state.

**Comment by Phanx091** [comment]
update again

**Comment by Phanx091** [comment]
updated 2

**Review by llenk — APPROVED** [review]

**Review by Phanx091 — COMMENTED** [review]
changes made on customer reducer

**Review by emily-kay — APPROVED** [review]
Looks great!

**Review by emily-kay — APPROVED** [review]

**Pull request merged**
